pipeline {
    agent any
environment{
    PATH = "/usr/bin:$PATH"
}
    stages {
        stage("clone git") {
            steps {
                git url: 'https://github.com/Bhavanaht5/C-project.git'
            }
        }
        stage("build") {
            steps {
               cd /home/ec2-user/jenkins/workspace/CProject/CProject/Build_CProject
                sh "make"
            }
        }
    }
}
