pipeline {
    agent any
environment{
    PATH = "/usr/bin:$PATH"
}
    stages {
        stage("build") {
            steps {
sh '''
#!/bin/bash
                git clone https://github.com/Bhavanaht5/C-project.git         
cd /home/ec2-user/jenkins/workspace/pipeline-1/CProject/Build_CProject/
                make
'''
            }
        }
            }
}
